# Workflow for building and deploying a Hugo site to GitHub Pages gh-pages branch
name: Deploy Hugo site to gh-pages

on:
  # Runs on pushes targeting the default branch (main)
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write # Needed by peaceiris/actions-gh-pages to push to gh-pages branch

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages" # Use "pages" group for standard Pages deployment concurrency
  cancel-in-progress: false # Allow production deployments to complete

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  # Build and Deploy job
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.145.0 # Use your desired Hugo version
      HUGO_ENVIRONMENT: production
      TZ: America/Los_Angeles # Optional: Set timezone

    steps:
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb

      - name: Install Dart Sass (if needed by your theme/site)
        run: sudo snap install dart-sass

      - name: Checkout main branch code
        uses: actions/checkout@v4
        with:
          submodules: recursive # Fetch submodules if needed (themes often are)
          fetch-depth: 0 # Fetch all history for .GitInfo and Lastmod

      # Removed: Setup Pages (actions/configure-pages@v5) - Not used with this deployment action

      - name: Install Node.js dependencies (if needed)
        run: "[[ -f package-lock.json || -f npm-shrinkwrap.json ]] && npm ci || true"

      - name: Build Hugo site
        # Build site to default './public' directory
        # Set baseURL for GitHub Project Pages: https://<username>.github.io/<repository>/
        run: |
          hugo \
            --gc \
            --minify \
            --baseURL "https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/"

      # Removed: Commit step using git-auto-commit-action

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Directory to deploy (Hugo builds to 'public' by default)
          publish_dir: ./public
          # The branch to deploy to
          publish_branch: gh-pages
          # Optional: Custom commit message for the gh-pages branch
          commit_message: "Deploy Hugo site to gh-pages (${{ github.sha }})" # Default is 'Deploy to GitHub Pages'
          # Optional: Set user for commit, defaults to github-actions[bot]
          # user_name: 'github-actions[bot]'
          # user_email: '41898282+github-actions[bot]@users.noreply.github.com'
          # Optional: Add a CNAME file if using a custom domain
          # cname: your.custom.domain.com